workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'test'
          include: true
          source: false 
      cancel_previous_builds: true
    environment:
      groups:
        - google_credentials
      flutter: stable
    scripts:
      - name: Setup the keystore
        script: |
          echo $KEYSTORE_FILE | base64 --decode > /tmp/keystore.jks
          cat > "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=upload
          storeFile=/tmp/keystore.jks
          EOF
      - name: Build AAB
        script: |
          cd $CM_BUILD_DIR
          flutter pub get
          flutter build appbundle --release --build-name="3.1.2" --build-number=28
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
        submit_as_draft: true
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'test'
          include: true
          source: false 
      cancel_previous_builds: true
    integrations:
      app_store_connect: codemagic test appstore connect
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.avalian.avapocket
      vars:
        APP_ID: 6618155014
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --build-name=3.1.2 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - pcarvi@avalian.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false